# Generated by Django 5.0.6 on 2024-06-19 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0017_doctor_phone_office_doctor_phone_office_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['doctor']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='schedule',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='doctors.schedule'),
        ),
    ]
