# Generated by Django 5.0.6 on 2024-06-18 05:17

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='cell_phone',
        ),
        migrations.AddField(
            model_name='patient',
            name='conf_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region='BR', unique=True),
        ),
    ]
