# Generated by Django 5.0.6 on 2024-06-18 05:18

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patient_cell_phone_patient_conf_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region='BR'),
        ),
    ]
