# Generated by Django 5.0.6 on 2024-05-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_address_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cell_phone',
            field=models.CharField(max_length=11),
        ),
    ]
