# Generated by Django 5.0.6 on 2024-05-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_cell_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='greet',
            field=models.CharField(default='Dra.', max_length=5),
        ),
    ]
