# Generated by Django 5.0.6 on 2024-05-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctor_greet'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='conf_email',
            field=models.BooleanField(default=False),
        ),
    ]
