# Generated by Django 5.0.6 on 2024-06-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_alter_evaluation_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='maps_link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
