# Generated by Django 5.0.6 on 2024-06-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_address_maps_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='maps_link',
            field=models.CharField(max_length=500),
        ),
    ]
