# Generated by Django 5.0.6 on 2024-06-18 05:18

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_remove_doctor_cell_phone_doctor_conf_cell_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region='BR'),
        ),
    ]
